"""
Global exception handlers for the Financial RAG API.

Maps internal exceptions to appropriate HTTP status codes and structured
JSON error bodies.  Centralising this here keeps route handlers free of
try/except boilerplate and ensures consistent error response shapes.

Error response body shape (always):
    {
        "error":      "<short human-readable category>",
        "detail":     "<longer explanation or original exception message>",
        "request_id": "<X-Request-ID for log correlation>"
    }

Handler priority: FastAPI matches the most-specific exception class first.
The catch-all Exception handler at the bottom should only be reached for
genuinely unexpected errors.

HTTP status code rationale:
  400 — Bad request: caller error (invalid query, unknown ticker)
  401 — Unauthenticated: bad OpenAI API key
  422 — Pydantic validation failure (auto-generated by FastAPI, overridden here)
  429 — Rate limited by OpenAI; Retry-After header set to 10s
  503 — Service unavailable: BM25 index or Qdrant collection not found
  504 — Gateway timeout: OpenAI API timed out after retries
  502 — Bad gateway: OpenAI unreachable (network / DNS)
  500 — Internal error: unclassified / unexpected
"""

from __future__ import annotations

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from loguru import logger
from openai import APIConnectionError, APITimeoutError, AuthenticationError, RateLimitError


def _rid(request: Request) -> str:
    """Extract the request trace ID, or '-' if not yet set by RequestIDMiddleware."""
    return getattr(request.state, "request_id", "-")


def _body(error: str, detail: str | None, request: Request) -> dict:
    return {"error": error, "detail": detail, "request_id": _rid(request)}


def register_exception_handlers(app: FastAPI) -> None:  # noqa: C901
    """Register all exception → HTTP status mappings on the FastAPI app."""

    # ── 422 Pydantic validation failures ──────────────────────────────────────
    @app.exception_handler(RequestValidationError)
    async def validation_handler(request: Request, exc: RequestValidationError) -> JSONResponse:
        logger.warning(f"[{_rid(request)}] Validation error | {exc.errors()}")
        return JSONResponse(
            status_code=422,
            content=_body("Validation error", str(exc.errors()), request),
        )

    # ── 400 Explicit ValueError from route handlers ────────────────────────────
    @app.exception_handler(ValueError)
    async def value_error_handler(request: Request, exc: ValueError) -> JSONResponse:
        logger.warning(f"[{_rid(request)}] Bad request | {exc}")
        return JSONResponse(
            status_code=400,
            content=_body("Bad request", str(exc), request),
        )

    # ── 401 OpenAI authentication failure ────────────────────────────────────
    @app.exception_handler(AuthenticationError)
    async def auth_handler(request: Request, exc: AuthenticationError) -> JSONResponse:
        logger.error(f"[{_rid(request)}] OpenAI auth failure | {exc}")
        return JSONResponse(
            status_code=401,
            content=_body(
                "LLM authentication failure",
                "Check that OPENAI_API_KEY is set and valid.",
                request,
            ),
        )

    # ── 429 OpenAI rate limit ─────────────────────────────────────────────────
    @app.exception_handler(RateLimitError)
    async def rate_limit_handler(request: Request, exc: RateLimitError) -> JSONResponse:
        logger.warning(f"[{_rid(request)}] OpenAI rate limit | {exc}")
        return JSONResponse(
            status_code=429,
            content=_body(
                "Rate limit exceeded",
                "The LLM provider is rate-limiting this service. Retry in a moment.",
                request,
            ),
            headers={"Retry-After": "10"},
        )

    # ── 503 BM25 index or Qdrant collection missing ────────────────────────────
    @app.exception_handler(FileNotFoundError)
    async def file_not_found_handler(request: Request, exc: FileNotFoundError) -> JSONResponse:
        logger.error(f"[{_rid(request)}] Resource missing | {exc}")
        return JSONResponse(
            status_code=503,
            content=_body(
                "Service unavailable",
                f"{exc}  —  Run `poetry run python -m ingestion.pipeline` first.",
                request,
            ),
        )

    # ── 504 OpenAI timeout ────────────────────────────────────────────────────
    @app.exception_handler(APITimeoutError)
    async def timeout_handler(request: Request, exc: APITimeoutError) -> JSONResponse:
        logger.error(f"[{_rid(request)}] LLM timeout | {exc}")
        return JSONResponse(
            status_code=504,
            content=_body(
                "Gateway timeout",
                "The language model API timed out after all retries. Please retry your request.",
                request,
            ),
        )

    # ── 502 OpenAI connection error ───────────────────────────────────────────
    @app.exception_handler(APIConnectionError)
    async def connection_handler(request: Request, exc: APIConnectionError) -> JSONResponse:
        logger.error(f"[{_rid(request)}] LLM connection error | {exc}")
        return JSONResponse(
            status_code=502,
            content=_body(
                "Bad gateway",
                "Could not connect to the language model API. Check network connectivity.",
                request,
            ),
        )

    # ── 500 Catch-all — should never be reached in normal operation ───────────
    @app.exception_handler(Exception)
    async def generic_handler(request: Request, exc: Exception) -> JSONResponse:
        logger.exception(f"[{_rid(request)}] Unhandled {type(exc).__name__}: {exc}")
        return JSONResponse(
            status_code=500,
            content=_body(
                "Internal server error",
                "An unexpected error occurred. Check server logs for details.",
                request,
            ),
        )
